#****************************************************************
#* lite-manager                                                 *
#* NOTE: do not edit this file as it is automatically generated *
#****************************************************************

CONFIG_SGL_PANEL_PIXEL_DEPTH = 32
CONFIG_SGL_EVENT_QUEUE_SIZE = 16
CONFIG_SGL_DIRTY_AREA_THRESHOLD = 64
CONFIG_SGL_DRAW_USE_DMA = n
CONFIG_SGL_COLOR16_SWAP = n
CONFIG_SGL_ANIMATION = y
CONFIG_SGL_ANIMATION_TICK_MS = 1
CONFIG_SGL_DEBUG = y
CONFIG_SGL_LOG_COLOR = y
CONFIG_SGL_LOG_LEVEL = 0
CONFIG_SGL_TEXT_UTF8 = n
CONFIG_SGL_OBJ_USE_NAME = y
CONFIG_SGL_USE_STYLE_UNIFIED_API = y
CONFIG_SGL_HEAP_ALGO = lwmem
CONFIG_SGL_FL_INDEX_MAX = 20
CONFIG_SGL_HEAP_MEMORY_SIZE = 40960
CONFIG_SGL_FONT_SONG23 = y
CONFIG_SGL_FONT_CONSOLAS23 = y
CONFIG_SGL_FONT_KAI33 = y
CONFIG_SGL_FONT_CONSOLAS14 = y

# Variables provided for Makefile
C_SOURCE := main.c sgl_port_sdl2.c ../sgl/source/core/sgl_core.c ../sgl/source/core/sgl_log.c ../sgl/source/core/sgl_math.c ../sgl/source/core/sgl_event.c ../sgl/source/core/sgl_anim.c ../sgl/source/mm/lwmem/lwmem.c ../sgl/source/mm/lwmem/sgl_mm.c ../sgl/source/draw/sgl_draw_line.c ../sgl/source/draw/sgl_draw_rect.c ../sgl/source/draw/sgl_draw_bar.c ../sgl/source/draw/sgl_draw_circle.c ../sgl/source/draw/sgl_draw_arc.c ../sgl/source/draw/sgl_draw_text.c \
            ../sgl/source/draw/sgl_draw_ring.c ../sgl/source/draw/sgl_draw_icon.c ../sgl/source/widgets/line/sgl_line.c ../sgl/source/widgets/rectangle/sgl_rectangle.c ../sgl/source/widgets/circle/sgl_circle.c ../sgl/source/widgets/ring/sgl_ring.c ../sgl/source/widgets/arc/sgl_arc.c ../sgl/source/widgets/button/sgl_button.c ../sgl/source/widgets/slider/sgl_slider.c ../sgl/source/widgets/label/sgl_label.c ../sgl/source/widgets/switch/sgl_switch.c ../sgl/source/widgets/msgbox/sgl_msgbox.c ../sgl/source/widgets/textline/sgl_textline.c ../sgl/source/widgets/textbox/sgl_textbox.c ../sgl/source/widgets/checkbox/sgl_checkbox.c ../sgl/source/widgets/listview/sgl_listview.c ../sgl/source/widgets/icon/sgl_icon.c ../sgl/source/widgets/numberkbd/sgl_numberkbd.c ../sgl/source/widgets/keyboard/sgl_keyboard.c ../sgl/source/fonts/sgl_ascii_song23.c ../sgl/source/fonts/sgl_ascii_consolas23.c ../sgl/source/fonts/sgl_ascii_consolas14.c ../sgl/source/fonts/sgl_ascii_kai33.c test.c bg.c

C_PATH := -Isdl/include/SDL2 -I../sgl/source -I../sgl/source/include

C_FLAG :=  -O2 -Wl,-Bstatic -ffunction-sections -fdata-sections -nostdlib -ffreestanding -Wunused-function -Wall -Wextra -Werror -std=c99  -g

LIB_NAME := -lmingw32 -lSDL2main -lSDL2.dll

LIB_PATH := -Lsdl/lib

